name: Deploy Ujwal Enterprises Website

# Trigger the workflow on push to main branch or manual dispatch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Environment variables
env:
  DOCKER_IMAGE_NAME: ujwal-enterprises-website
  DOCKER_TAG: latest

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} .
    
    - name: Test Docker image
      run: |
        # Run the container in detached mode
        docker run -d --name test-container -p 8080:80 ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        
        # Wait for container to start
        sleep 10
        
        # Test if website is accessible
        curl -f http://localhost:8080 || exit 1
        
        # Clean up
        docker stop test-container
        docker rm test-container
    
    - name: Save Docker image as artifact
      run: |
        docker save ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} | gzip > ujwal-website-image.tar.gz
    
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: ujwal-website-image.tar.gz
        retention-days: 1

  # Job 2: Deploy to Production (only on main/master branch)
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    
    - name: Load Docker image
      run: |
        docker load < ujwal-website-image.tar.gz
    
